spring:
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
  application:
    name: HeightApp

  datasource:
    url: jdbc:h2:mem:HeightDB
    username: sa
    password: sa
  h2:
    console:
      enabled: true

server:
  port: 8080

